import React from "react";
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import {signIn, signOut, useSession} from 'next-auth/react'
import { Session } from "inspector";
const Header=()=>{
    const {data,status} = useSession()
    console.log(data,status)
    const HandleSignIn=()=>{
        return (
            signIn('github', {
                prompt:'select_account',
                callbackUrl:'https://gitcon.herokuapp.com/dashboard',
            })
        )
    }
   
    return(
        <div className={styles.container}>
      <Head>
        <title>Git Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to GitCon
        </h1>

        <p className={styles.description}>
          Connect to you github account
        </p>
        <button className={styles.button} onClick={HandleSignIn}>Signup to Github</button>
      </main>

      <footer className={styles.footer}>
          Designed by Snipper 
      </footer>
    </div>
    )
}

export default Header